### ISSUE TITLE
跑不出结果来！

### ISSUE THREAD

**Issue by yangshulin0017** [sshuangliu/auto_config_get#1]
[Python求助.docx](https://github.com/sshuangliu/auto_config_get/files/9966476/Python.docx)

跑完以后没有结果。能帮忙看一下吗

**Comment by sshuangliu** [comment]
python3.8 netmiko 3,x， 其他环境没有测试过

1： Cisco 设备，登录需要用户名 密码
2: h3c 设备
下列这句
"device_type": "cisco_ios" if device['ssh_telnet'] == "ssh" else "cisco_ios_telnet",

"cisco_ios"和 "cisco_ios_telnet"  换为’hp_comware‘  和 ’hp_comware_telnet‘  试试

3: huawei 设备
下列这句
"device_type": "cisco_ios" if device['ssh_telnet'] == "ssh" else "cisco_ios_telnet",

"cisco_ios"和 "cisco_ios_telnet"  换为’huawei‘  和 ’huawei_telnet‘  试试




@@@@@@@@@@ssh@@@@@@@@@@@@

>>> net_connect = ConnectHandler(**cisco1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 360, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
aruba_os
aruba_osswitch
aruba_procurve
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
coriant
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
dlink_ds
eltex
eltex_esr
endace
enterasys
ericsson_ipos
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
flexvnf
fortinet
generic
generic_termserver
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_vrpv8
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
linux
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
sixwind_os
sophos_sfos
supermicro_smis
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os



@@@@@@@@@@@@@@telnet@@@@@@@@@@@@@@

>>> net_connect = ConnectHandler(**cisco1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 360, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
adtran_os_telnet
apresia_aeos_telnet
arista_eos_telnet
aruba_procurve_telnet
audiocode_66_telnet
audiocode_72_telnet
audiocode_shell_telnet
brocade_fastiron_telnet
brocade_netiron_telnet
calix_b6_telnet
centec_os_telnet
ciena_saos_telnet
cisco_ios_telnet
cisco_s300_telnet
cisco_xr_telnet
dell_dnos6_telnet
dell_powerconnect_telnet
dlink_ds_telnet
extreme_exos_telnet
extreme_netiron_telnet
extreme_telnet
generic_telnet
generic_termserver_telnet
hp_comware_telnet
hp_procurve_telnet
huawei_olt_telnet
huawei_telnet
ipinfusion_ocnos_telnet
juniper_junos_telnet
nokia_sros_telnet
oneaccess_oneos_telnet
paloalto_panos_telnet
rad_etx_telnet
raisecom_telnet
ruckus_fastiron_telnet
ruijie_os_telnet
supermicro_smis_telnet
tplink_jetstream_telnet
yamaha_telnet
zte_zxros_telnet
>>> net_connect.disconnect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'net_connect' is not defined
